### ISSUE TITLE
Request: Iteration on nested arrays

### ISSUE THREAD

**Issue by nigelbalchin** [preciousforever/data-populator#100]
Hi - is there a mechanism to allow iteration on nested arrays of JSON data? I don't want to have to index individual elements in the array in line with your responses on Request: Nested arrays #49 / Not recognising nested data #45 - I'd like to iterate by default. Is this achievable?
Cheers

[
 {
   "givenName": "John",
   "surName": "Smith",
   "phones": [
      {
         "type":     "Mobile",
         "number":   "23344556"
      },
      {
         "type":     "Fixed",
         "number":   "6777-4556"
      }
   ]
 }
]

**Comment by chanjohnathan** [comment]
I'm not sure if this is similar enough to this feature, but it would be nice to be able to randomize nested objects, rather than creating specific objects.

Similar to:
```
[
	{
		"status": {
			"status1": "Active",
			"status2": "Upcoming",
			"status3": "Cancelled"
		},
		"type": {
			"type1": "Free",
			"type2": "Paid"
		}
	}
]
```

**Comment by adamdiestelkamp** [comment]
This would be a really nice feature. As another example It'd be great to be able to use a single symbol for a bar chart with a value of `{data[i]}` and have it iterate through the array 
`"data":[ 10, 20, 45, 78, 21]` automatically. Right now I can't make each bar a a symbol because I have to explicitly call out {value[0]}, {value[1]}, etc.

![image](https://user-images.githubusercontent.com/4571734/47098545-02de8700-d1f9-11e8-8976-03a671047a90.png)

This is a great tool, thanks for building it!

**Comment by nitrada** [comment]
@adamdiestelkamp great idea! it's open source, feel free to contribute the feature! =)

**Comment by nitrada** [comment]
@chanjohnathan i'm not sure what you mean exactly. your example already works if you use `{status.status1}` or `{type.type1}` etc.

Please refer to #45 and #49

**Comment by sirpooya** [comment]
Guys it's 2020 & I have the exact same issue here, iteration on array of nested objects with no individual index as @nigelbalchin said.
It's very practical when working with complex real JSON APIs.

Would you please mark this as High Priority?

**Comment by nitrada** [comment]
@sirpooya there are currently no plans to add this in the near future. please get in touch if you know someone who'd like to contribute, or a sponsor that could be interested and we will have a look into adding it.
