### ISSUE TITLE
Plugin command?

### ISSUE THREAD

**Issue by meaziz** [preciousforever/data-populator#128]
This is not an issue per say.
The problem is I'm trying to create a grid of cards where the image represents a map
I'am using the Map Generator Plugin. -> https://github.com/eddiesigner/sketch-map-generator

Following the guide the layer name should be 
#plugin[true, Map Generator > Generate a Map Using Google Maps]

I thing the command path I'm using is not right but can't find a way to know it.

Any help?

**Comment by danscriptive** [comment]
+1

**Comment by nitrada** [comment]
@meaziz 
we never tried that combination of plugins. will have a look.

**Comment by nitrada** [comment]
doesn't work here neither – it seems the "plugin" command is broken (as I also didn't manage to run any other plugin). getting this error message:

![image](https://user-images.githubusercontent.com/1927315/41203414-a430ffa8-6cd6-11e8-918f-fff5d5f5d302.png)

@lukasondrej do you have an idea?

**Comment by ohnoimdead** [comment]
I'm not sure this would work right now anyway because I believe the map generator plugin would need to look for the location data in the layer's metadata where the data populator stashes it. Take a look at:
https://github.com/preciousforever/sketch-data-populator/blob/c5f7fa550d01b77361ceb78b4e73817c62062780/src/library/actions/plugin.js#L95-L105

Currently sketch-map-generator only receives input from the dialog it pops: https://github.com/eddiesigner/sketch-map-generator/blob/8235cc62dff894ee93d3b11333d420e9095776b5/Map%20Generator.sketchplugin/Contents/Sketch/google.js

Might be possible to modify sketch-map-generator to support a non-gui command that looks for the data this plugin stashes.
