### ISSUE TITLE
Data Populate Overide Settings - Attached Sketch File

### ISSUE THREAD

**Issue by creativechris08** [preciousforever/data-populator#160]
**Which version of the plugin are you using?**
[ x ] Data Populator for Sketch
[ ] Data Populator for Adobe XD

**Is your feature request related to a problem? Please describe.**
Allowing override population will enable us to use the same symbol but different key results [...]

**Describe the solution you'd like**
Manually set key values in override panel, run the plugin with presets to populate and override key values

**Describe alternatives you've considered**
-

**Additional context**
Ive attached a sketch example file with the results that i would like :)
[Overide_datapopulator.sketch.zip](https://github.com/preciousforever/data-populator/files/2515666/Overide_datapopulator.sketch.zip)

**Comment by creativechris08** [comment]
We’re using the latest 52.2 👍🏻😎

**Comment by creativechris08** [comment]
And latest plugin

**Comment by nitrada** [comment]
@creativechris08 ok, so you need to use the {placeholder} in the layer name of the text layer, not the content of the override and it should work just fine!

**Comment by creativechris08** [comment]
This is know :) but this was a feature request to be able to have this option! Would this be possible or?

**Comment by creativechris08** [comment]
Please refer to attached sketch file. Using override text keys will allow the use for using One symbol but with many text key options. Something that is not currently possible using data populatior

**Comment by creativechris08** [comment]
I want to use only one symbol with (placeholder) text but have say 3 separate values without the order being random or having to use the plugin to create the grid. How would this be possible?

**Comment by nitrada** [comment]
@creativechris08 ok, we already had this feature request before. This would be helpful if you for example want a *single symbol* in which you always have e.g. an image, a H1, a H2 and a Description. but in Case 1 you want it to be a Contact, in Case 2 a Product and they don't share the same key names – so you need to put the {placeholders} in the overrides. Right now, you need to define a Symbol for "Contact" and one for "Products".

on the other hand, it's already possible to have the order in the JSON in the populated grid. because the {placeholder} would always be {name}, but it will populate the grid sequentially along the order in the JSON (if random is 'off'). or maybe i don't get your point.

**Comment by nitrada** [comment]
#94 is the original feature request.

**Comment by nitrada** [comment]
@creativechris08 see #94 – we're trying to get this running in the next version…

**Comment by nitrada** [comment]
@creativechris08 please check out v3.0.3!
https://www.datapopulator.com/sketch/changelog.html
