### ISSUE TITLE
Feature Request: Allow JSON to fill object color

### ISSUE THREAD

**Issue by christoyc** [preciousforever/data-populator#97]
I manage color stories and themes in a spreadsheet. It would be awesome to be able to fill the color of a object from the HEX or RGB value in the JSON to instantly create a color styleguide. BTW, I love love love your plugin. Thank you so much for your work.

**Comment by Mokhova** [comment]
Hi!
Is there any news on this yet?

**Comment by rohr** [comment]
@nitrada your plugin is excellent. Regarding this issue, is the plan to have this functionality? It's is marked as "Won't do", but the documentation shows:
```
#swapSymbol[true, bg/{color}]
// swaps the affected symbol to 'bg/red' (assuming {color} delivers 'red' from the data).
'true' can be replaced with any conditional expression.
```
I am confused as to whether this is currently available.

**Comment by nitrada** [comment]
@rohr thanks for the nice words!

the example you referenced is the #SwapSymbol conditional action, which is a generic way to swap a symbol based on a certain condition – eg if the string in the data contains a certain content (eg. “blue”) or amount of characters, swap the symbol to symbol XY (eg. symbol name “blue”). 

so in the example, the {color} placeholder is being used to set the symbol name – it could also be {whatever} though, _color_ is just an example here.

the part we won’t do is using hex values in data to set hex values for objects in Sketch, because we think that’s too specific and we don’t need it for our own requirements. but feel free to change or extend the plugin to your liking, it’s open source and the architecture is quite a accessible and modular.
